const ApiUrl = {
  APPUPDATEURL:'auth/download_real_rstate',
  LOGIN: 'auth/log-in',
  VERIFY_OTP: 'auth/verify-otp',
  FORGOT_PASSWORD: 'auth/forgot-password',
  VERIFY_FORGOT: 'auth/forgot-password-verify',
  CREATE_PASSWORD: 'auth/reset-password',
  PROFILE: 'Employees/profile',
  EDITPROFILE: 'auth/editProfile',

  LeadDashBoard: 'Lead/dashboard',
  EmployeeLocationTrack: 'Employees/locationTruck',

  PropertyType: 'Projects/propertyType',
  PropertyConditions: 'Projects/propertyConditions',
  OwnershipType: 'Projects/ownershipType',
  ADDPROJECT: 'Projects/CreateProject',
  ProjectList: 'Projects/projectList?',
  ProjectStatus: 'Projects/projectStatus/',
  projectImageList: 'Projects/projectImageList/',
  ProjectassignProject: 'Projects/assignProject',
  ProjectassignToEmployeeList: 'Projects/assignedToEmployeeList/',
  ProjectCertificateList: 'Projects/certificateDropdrone',
  ProjectAddFlats: 'Projects/addFlatSize/',
  ProjectAssignedToEmployee:"Projects/projectAssignedToEmployee/",
  AddProductImages: 'Projects/addProjectImage/',
  ProjectProfileUpdate: 'Projects/projectProfileUpdate/',
  DeleteProjectImage: 'Projects/deleteProjectImage/',
  DeleteAssignedEmployee: 'Projects/deleteAssignedEmployee/',
  EditProjectApi: 'Projects/editProject/',
  employeeListApi: 'Projects/employeeList',
  LeadStatusListApi: 'Lead/LeadStatusList',
  LeadSourceListApi: 'Lead/leadSourceList',
  LeadLocationPreference: 'Lead/locationPreference',
  LeadTimelineapi: 'Lead/timeline',
  LeadLabelApi: 'Lead/leadLabel',
  LeadProjectList: 'Lead/projectList',
  LeadCreateApi: 'Lead/createLead',
  LeadQuickCreateApi: 'Lead/createQuickLead',
  LeadEditApi: 'Lead/editLead/',
  LeadListApi: 'Lead/leadList?',
  LeadDetailsApi: 'Lead/leadDetail/',
  RemarkListApi: 'Lead/remarkList',
  LeadTimelistApi: 'Lead/leadTimelineList/',
  AssignLeadApi: 'Lead/assignLead',
  AssignAddLeadApi: 'Lead/addLeadTimeline',
  LeadFilterApi: 'Lead/leadFilter?',
  StartVisitAPI: 'Lead/startVisit/',
  LeadENDVISITAPI:"Lead/endVisit/",
  MakeCallAPI: 'Lead/makeCall/',
  //Lead
  LeadAssignAllAPI: 'Lead/allEmployee?leadId=',
  LeadShareApi: 'Lead/shareLead',
  LeadDropDownApi: 'Lead/dropdrone',
  LeadStatusAPI: 'Lead/leadStatus/',
  LeadInceviteAddApi: 'salary/leadClose_addIncentive',
  LeadAssignEmployee:"Lead/assignedToEmployeeList/",
  LeadunAssignedEmployeeList:'Lead/unAssignedEmployeeList/',
  LeadShuffleApi:'Lead/shuffleLead',
  LeadAssignDelete:"Lead/deleteAssignedToEmployee/",
  LeadImportExcel:'Lead/createExcellLead',
  HomePageLeadApi:"Lead/homePageleadList?leadStatus=9",

  //Employees
  AddEmployees: 'Employees/addEmployee',
  EditEmployees: 'Employees/editEmployee/',
  AllEmployee: 'Employees/allEmployee',
  EmployeeStatus: 'Employees/employeeStatus/',
  DeleteEmployee: 'Employees/deleteEmployee/',
  EmployeeDetailsScreen: 'Employees/employeeDetails/',
  EmployeeAttendanceScreen: 'Employees/attendance',
  EmployeeAttendanceCheck: 'Employees/checkDayAttendance/',
  EmployeeAttendanceList: 'Employees/attendanceList/',
  EmployeeTimelineActivity: 'Employees/TimelineActivity?empId=',
  EmployeeMessageList: 'Employees/messageEmpList',
  EmployeeSingleMessageList: 'Employees/messageList?empId=',
  EmployeeSendMessage: 'Employees/sendMessage',
  EmployeeMessageStatusApi: 'Employees/updateMessageStatus?empId=',
  EmployeeRoleApi: 'Employees/admin_And_HR',
  //
  SalaryListApi: 'salary/salaryList?empId=',
  SalaryAdvanceApi: 'salary/advancedSalaries',
  SalarySilpDownload:'salary/salarySlip?employee_id=',
  EmployessSummeryReport:'Lead/summeryReport?empId=',
  EmployessIncentiveHistory:'Lead/incentiveHistory?empId=',
  


  //HolidayList
  HolidayListScreen: 'Employees/CalendarList',
  HolidayAddScreen: 'Employees/addHoliday',
  //Leave
  LeaveTypeDropdown: 'Employees/leaveTypeDropdown',
  LeaveRequestApi: 'Employees/leaveRequest',
  LeaveListApi: 'Employees/leaveList',
  LeaveStatusApi: 'Employees/leaveStatus/',
  EmployeeNotificationApi: 'Employees/notification',
  EmployeeUNReadApi: 'Employees/unreadNotifications',

  AppVersionApi:"Employees/appVersion",
  BadgeCountApi:'Lead/unVisitLeadProject'
};

export default ApiUrl;
